providers = []

[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run prisma:generate --workspace=apps/api",
  "npm run build --workspace=apps/api"
]

[start]
cmd = "npm run prisma:migrate:deploy --workspace=apps/api && npm run start:prod --workspace=apps/api"