[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npx prisma generate --schema=apps/api/prisma/schema.prisma",
  "npm run build --workspace=apps/api"
]

[start]
cmd = "npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma && npm run start:prod --workspace=apps/api"
