// Used against the temporary local Next review route (removed after review).
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
async function main() {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let logouts = 0;
  await page.route('**/api/checkin/session/logout', async route => { logouts++; await route.fulfill({ json: {} }); });
  await page.route('**/api/checkin/visual-fixture/logo', route => route.fulfill({ path: path.resolve('apps/web/public/flikker-wordmark.svg') }));
  await page.goto('http://127.0.0.1:3001/loyalty-visual-review');
  await page.getByRole('button', { name: 'Cambiar de cuenta' }).click();
  await page.locator('[data-review-switched]').waitFor();
  assert.equal(logouts, 1);
  await page.getByRole('button', { name: 'Alternar panel' }).click();
  await page.getByLabel('Color principal / encabezado', { exact: true }).fill('#173c32');
  await page.getByLabel('Color de los sellos completados', { exact: true }).fill('#147a5b');
  await page.getByRole('button', { name: 'Tijera', exact: true }).click();
  const card = page.locator('[data-loyalty-layout=experience]');
  assert.equal(await card.locator('[data-stamp-state] .lucide-scissors').count(), 6);
  assert.equal(await card.evaluate(node => node.style.backgroundColor), 'rgb(23, 60, 50)');
  assert.equal(await card.locator('[data-stamp-state=completed]').first().evaluate(node => node.style.backgroundColor), 'rgb(20, 122, 91)');
  assert.equal(await card.locator('[data-stamp-state=empty]').first().evaluate(node => node.style.backgroundColor), 'transparent');
  await page.getByRole('button', { name: 'Guardar diseño', exact: true }).click();
  let patch = JSON.parse(await page.locator('[data-review-save]').textContent());
  assert.equal(patch.loyaltyCardColor, '#173C32');
  assert.equal(patch.loyaltyStampColor, '#147A5B');
  assert.equal(patch.loyaltyStampIcon, 'scissors');
  const iconFile = page.locator('label').filter({ hasText: 'Subir ícono personalizado' }).locator('input');
  await iconFile.setInputFiles({ name: 'custom-stamp.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><path d="M32 4L60 32 32 60 4 32Z" fill="black"/></svg>') });
  await card.locator('[data-custom-stamp=outline]').first().waitFor();
  assert.equal(await card.locator('[data-custom-stamp=outline]').count(), 4);
  await page.getByRole('button', { name: 'Guardar diseño', exact: true }).click();
  patch = JSON.parse(await page.locator('[data-review-save]').textContent());
  assert.ok(patch.loyaltyStampIcon.startsWith('data:image/svg+xml'));
  await page.screenshot({ path: path.join(__dirname, 'live-panel-updated.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 812 });
  await page.getByRole('button', { name: 'Ver preview', exact: true }).click();
  assert.equal(await page.locator('[data-loyalty-layout=experience]:visible').count(), 1);
  await page.screenshot({ path: path.join(__dirname, 'live-panel-mobile.png'), fullPage: true });
  await page.goto('http://127.0.0.1:3001/loyalty-visual-review');
  await page.getByRole('link', { name: 'Mis lugares y premios' }).click();
  await page.waitForURL('**/mi-flikker');
  assert.deepEqual(errors, []);
  fs.writeFileSync(path.join(__dirname, 'browser-result.json'), JSON.stringify({ logoutRequests: logouts, savedBrandColor: patch.loyaltyCardColor, savedStampColor: patch.loyaltyStampColor, customIconSaved: true, mobilePreviewOpened: true, navigation: page.url(), consoleErrors: errors }, null, 2));
  await browser.close();
  console.log('Browser checks passed: switch account, real navigation, editor colors/icon, save payload, custom stamp upload and mobile preview.');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
