import { Prisma } from '@prisma/client';

/**
 * Single source of truth for the four dashboard metrics. Every screen (panel,
 * "Tu QR", insights) must build its queries from here so the same word never
 * means two different things in two places.
 *
 * Definitions:
 *  - Escaneos: QR scan events of the business's capture campaign.
 *  - Contactos: UNIQUE PEOPLE captured through Flikker (one row per person,
 *    identified by phone). Scanning twice does not create two contacts.
 *  - Reseñas de Google: every review synced from Google, including the
 *    history that predates Flikker.
 *  - Reseñas desde Flikker: Google reviews posted since the business started
 *    using Flikker. This is a CONTEXT metric, not proof of causation — it must
 *    never be labelled "generadas por Flikker".
 */

/** Fields needed to resolve when a business started using Flikker. */
export interface FlikkerStartInput {
  businessCreatedAt: Date;
  /** Earliest plan the business ever had, if any. */
  firstPlan: { trialStart: Date | null; startDate: Date | null } | null;
}

/**
 * When this business started using Flikker. Anything older is pre-existing
 * history (imported Google reviews, contacts loaded by hand) and must never be
 * counted as a Flikker result.
 *
 * The first plan is what marks the real start of the relationship; the business
 * row can be created earlier while it is still being set up. We take the
 * earliest of the two known signals so the window is never wider than reality.
 */
export function resolveFlikkerStartAt(input: FlikkerStartInput): Date {
  const planStart = input.firstPlan?.trialStart ?? input.firstPlan?.startDate;
  if (!planStart) return input.businessCreatedAt;
  return planStart > input.businessCreatedAt
    ? planStart
    : input.businessCreatedAt;
}

/**
 * Contacts captured through Flikker's QR. Scoped to the tenant, restricted to
 * active rows (deleting a contact is a soft delete — `isActive: false` — and a
 * deleted contact must stop counting) and to the Flikker era.
 */
export function flikkerContactsWhere(
  businessId: string,
  flikkerStartAt: Date,
): Prisma.CustomerWhereInput {
  return {
    businessId,
    origin: 'qr',
    isActive: true,
    createdAt: { gte: flikkerStartAt },
  };
}

/**
 * Google reviews posted since the business started using Flikker.
 * NOT "generated by Flikker" — just the reviews that arrived during the period.
 */
export function reviewsSinceFlikkerWhere(
  businessId: string,
  flikkerStartAt: Date,
): Prisma.GoogleReviewWhereInput {
  return {
    businessId,
    postedAt: { gte: flikkerStartAt },
  };
}

/**
 * Counts unique people from a set of contact rows. The Customer table has no
 * unique constraint on (businessId, phoneE164) — only an index — so the same
 * person can legitimately end up with more than one row (for example when an
 * older row was soft-deleted and the public capture form, which only looks up
 * active rows, created a fresh one). Counting rows would inflate the metric.
 */
export function countUniquePeople(
  contacts: Array<{ phoneE164: string | null }>,
): number {
  const seen = new Set<string>();
  let withoutPhone = 0;

  for (const contact of contacts) {
    const phone = contact.phoneE164?.trim();
    if (!phone) {
      // No phone means there is no way to tell people apart — count the row on
      // its own rather than collapsing unrelated records together.
      withoutPhone += 1;
      continue;
    }
    seen.add(phone.toLowerCase());
  }

  return seen.size + withoutPhone;
}
