-- AlterTable
ALTER TABLE "Plan" ADD COLUMN     "messageQuotaMonthly" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "priceUsd" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "setupFeeUsd" INTEGER NOT NULL DEFAULT 0;
