// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// El import de solo-efecto ("dotenv/config") no estaba garantizando
// `process.env.DATABASE_URL` a tiempo para `prisma migrate status`/`deploy`
// (sí para `prisma generate`, que no necesita conexión real) — causaba
// "The datasource.url property is required", con `DATABASE_URL` real y
// correcto esperando en `.env` sin usarse. `config()` explícito, con la ruta
// resuelta contra `__dirname` (no contra `process.cwd()`, que puede variar
// según desde dónde se invoque `npx prisma ...`), lo deja determinístico.
import { config } from "dotenv";
import path from "node:path";
import { defineConfig } from "prisma/config";

config({ path: path.resolve(__dirname, ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node -r tsconfig-paths/register prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
